### ISSUE TITLE
Tutorial refreshes page on mobile

### ISSUE THREAD

**Issue by sdao-tx** [sveltejs/learn.svelte.dev#547] opened 2023-12-22 12:47 UTC
On mobile phones using Safari, Chrome or Firefox, the Svelte tutorial automatically refreshes the page every 5 seconds. This makes it impossible to learn Svelte.

**Comment by geoffrich** [comment] 2023-12-22 16:29
Duplicate of https://github.com/sveltejs/learn.svelte.dev/issues/416

**Closed by geoffrich** 2023-12-22 16:29 UTC
