### ISSUE TITLE
Textarea Tutorial is broken

### ISSUE THREAD

**Issue by sirajulm** [sveltejs/learn.svelte.dev#154] opened 2022-12-15 23:10 UTC
Tutorial is unable to access `marked` npm package.
https://learn.svelte.dev/tutorial/textarea-inputs

```
[plugin:vite:import-analysis] Failed to resolve import "marked" from "src/lib/App.svelte". Does the file exist?
20 |  } from "svelte/internal";
21 |  
22 |  import { marked } from 'marked';
   |                          ^
23 |  const file = "src/lib/App.svelte";
```

**Comment by Conduitry** [comment] 2022-12-15 23:11
Duplicate of #141.

**Closed by Conduitry** 2022-12-15 23:11 UTC
