### ISSUE TITLE
The docs reload continuously

### ISSUE THREAD

**Issue by DCzajkowski** [sveltejs/learn.svelte.dev#558] opened 2024-01-05 13:45 UTC
Tested on mobile Safari, iOS 17.2.1.

Visiting subpages of learn.svelte.dev causes full-page reloads every few seconds.

https://github.com/sveltejs/learn.svelte.dev/assets/4501047/9cfa9614-a9b7-4606-a5ef-c6b5de6465a0

**Comment by geoffrich** [comment] 2024-01-05 16:54
Duplicate of https://github.com/sveltejs/learn.svelte.dev/issues/416.

This is a problem with the tutorial on learn.svelte.dev specifically. The static docs at kit.svelte.dev should not have this problem (e.g. https://kit.svelte.dev/docs/page-options#csr)

**Closed by geoffrich** 2024-01-05 16:54 UTC
