### ISSUE TITLE
Error in Safari 

### ISSUE THREAD

**Issue by JussMor** [sveltejs/learn.svelte.dev#428] opened 2023-07-14 00:09 UTC
### Describe the bug

![IMG_4999](https://github.com/sveltejs/svelte/assets/58856213/235ed61d-8b7e-4ff5-9512-c238c49ffe66)

### Reproduction

Go to:
https://learn.svelte.dev/tutorial/ssr

Wait some sec.
Page reload alone
Wait some sec 
Read mode appear some secs
Wait some sec
Page break 

### System Info

```shell
iPhone 13 Pro Max
```

### Severity

annoyance

**Comment by kobe-ra** [comment] 2023-07-15 10:17
The same goes for chrome on the ios. You can avoid it by constantly scrolling at a low speed but it's for sure still annoying.

**Comment by geoffrich** [comment] 2023-07-17 22:43
Duplicate of #416

**Closed by geoffrich** 2023-07-17 22:43 UTC
