### ISSUE TITLE
Tutorial crashes on iOS Safari

### ISSUE THREAD

**Issue by dwaltrip** [sveltejs/learn.svelte.dev#578] opened 2024-02-10 17:53 UTC
The tutorial page is repeatedly crashing for me.

This is what I see:

![IMG_4034](https://github.com/sveltejs/learn.svelte.dev/assets/3523411/fa29b302-f704-4f9a-a3ad-034e6b79041b)

This happens consistently as I read the tutorial, making it pretty unusable. I’m using Safari on an iPhone. It’s a 2020 iPhone SE with iOS 17.2.1.

If I can provide any additional info, let me know.

**Comment by Conduitry** [comment] 2024-02-10 17:58
Duplicate of #493.

**Closed by Conduitry** 2024-02-10 17:58 UTC
