### ISSUE TITLE
Bug in Tutorial

### ISSUE THREAD

**Issue by andronasef** [sveltejs/learn.svelte.dev#146] opened 2022-12-15 07:55 UTC
![image](https://user-images.githubusercontent.com/41882346/207803512-ecc8831c-9c41-431a-9070-f5534668696f.png)

[Issue](https://learn.svelte.dev/tutorial/textarea-inputs)
[Tutorial in Github](https://github.com/sveltejs/learn.svelte.dev/tree/main/content/tutorial/01-svelte/06-bindings/05-textarea-inputs)

**Comment by dummdidumm** [comment] 2022-12-15 12:48
Duplicate of #141

**Closed by dummdidumm** 2022-12-15 12:48 UTC
