### ISSUE TITLE
A possible issue with the handleError chapter of the SvelteKit tutorial

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/learn.svelte.dev#586] opened 2024-02-20 16:13 UTC
### Discussed in https://github.com/sveltejs/kit/discussions/11872

<div type='discussions-op-text'>

<sup>Originally posted by **brucegl** February 20, 2024</sup>
Hi,

In [https://learn.svelte.dev/tutorial/handleerror](https://learn.svelte.dev/tutorial/handleerror), is the "solve" solution meant to handle the unexpected error gracefully when you navigate to "the bad place"? Nothing happens for me.... maybe I misunderstood something.

Thanks
Gary</div>

**Comment by eunjs71** [comment] 2024-04-30 07:53
It seems I am also experiencing issues with this page. Navigating to /the-bad-place results in the following screen:

![Screenshot 2024-04-30 at 4 50 02 PM](https://github.com/sveltejs/learn.svelte.dev/assets/6983182/8f8970a9-73ea-4f36-a543-32362cc43be3)

**Comment by CrazyKidJack** [comment] 2024-09-28 15:54
is this related to https://github.com/sveltejs/learn.svelte.dev/issues/536 ?

**Comment by teemingc** [comment] 2024-09-28 17:16
> is this related to #536 ?

It is, good find. Closing as duplicate of #536

**Closed by teemingc** 2024-09-28 17:16 UTC
Labels: bug
